export type GlossaryCategory = "Vendas" | "SaaS" | "Marketing" | "IA" | "Produto digital";

export interface GlossaryTerm {
  term: string;
  category: GlossaryCategory;
  meaning: string;
  purpose: string;
  example: string;
  whenNeeded: string;
  nextStep: string;
}

export const glossary: GlossaryTerm[] = [
  {
    term: "SaaS",
    category: "SaaS",
    meaning: "Software como serviço. É um programa que você acessa pela internet pagando uma assinatura, em vez de comprar e instalar.",
    purpose: "Resolver um problema específico de forma contínua, recebendo todo mês pelo acesso.",
    example: "Netflix, Spotify e Canva são SaaS. Você paga por mês e usa pelo navegador.",
    whenNeeded: "Depois. Só vale criar quando você já entende a dor que quer resolver.",
    nextStep: "Antes de criar um SaaS, valide a ideia conversando com pessoas que sentem o problema.",
  },
  {
    term: "Micro-SaaS",
    category: "SaaS",
    meaning: "Uma versão pequena e focada de SaaS, geralmente feita por uma pessoa só, resolvendo uma dor bem específica.",
    purpose: "Gerar renda recorrente sem precisar de equipe grande nem investimento alto.",
    example: "Um app simples que gera legendas de Instagram para nutricionistas, cobrando R$29/mês.",
    whenNeeded: "Quando você já testou a ideia e quer transformar em produto.",
    nextStep: "Comece pela trilha Micro-SaaS para mapear uma dor específica.",
  },
  {
    term: "MVP",
    category: "Produto digital",
    meaning: "Produto Mínimo Viável. A versão mais simples do seu produto que já entrega valor.",
    purpose: "Lançar rápido, testar com pessoas reais e aprender antes de gastar tempo demais.",
    example: "Em vez de um app completo, você lança uma planilha que faz o essencial.",
    whenNeeded: "Agora. MVP é como você sai do plano e começa a vender.",
    nextStep: "Defina a menor versão possível do seu produto que alguém pagaria por ela.",
  },
  {
    term: "API",
    category: "SaaS",
    meaning: "É a forma de dois programas conversarem entre si, trocando dados de forma automática.",
    purpose: "Conectar serviços, automatizar tarefas e integrar ferramentas.",
    example: "Quando o iFood mostra o mapa do Google, ele usa a API do Google Maps.",
    whenNeeded: "Depois. Só vai precisar quando estiver montando algo técnico.",
    nextStep: "Por enquanto, foque em validar a ideia. API entra na etapa de construção.",
  },
  {
    term: "Webhook",
    category: "SaaS",
    meaning: "Um aviso automático que um sistema envia para outro quando algo acontece.",
    purpose: "Disparar ações em tempo real sem precisar ficar checando manualmente.",
    example: "Quando alguém compra na sua loja, um webhook avisa o WhatsApp para enviar a mensagem.",
    whenNeeded: "Depois, quando você estiver montando automações de verdade.",
    nextStep: "Anote o conceito e volte aqui quando começar a usar ferramentas como Make ou Zapier.",
  },
  {
    term: "Lead",
    category: "Vendas",
    meaning: "Uma pessoa que demonstrou interesse no seu produto, deixando um contato ou seguindo você.",
    purpose: "Transformar curiosos em clientes ao longo do tempo.",
    example: "Quem baixa seu ebook gratuito vira um lead que você pode contatar depois.",
    whenNeeded: "Agora. Começar a juntar leads desde o dia 1 acelera tudo.",
    nextStep: "Crie uma forma simples de capturar contatos, como um formulário ou link na bio.",
  },
  {
    term: "Funil",
    category: "Vendas",
    meaning: "O caminho que uma pessoa percorre, desde te conhecer até comprar de você.",
    purpose: "Organizar a jornada do cliente e melhorar a conversão em cada etapa.",
    example: "Vídeo no TikTok leva para o link na bio, que leva para uma página de venda.",
    whenNeeded: "Agora. Mesmo o funil mais simples já ajuda a vender mais.",
    nextStep: "Desenhe seu funil em 3 etapas: descoberta, interesse e compra.",
  },
  {
    term: "Copy",
    category: "Marketing",
    meaning: "Texto escrito para convencer alguém a fazer uma ação, como clicar ou comprar.",
    purpose: "Vender com palavras, sem precisar empurrar o produto.",
    example: "O texto da página de venda de um curso é uma copy.",
    whenNeeded: "Agora. Toda página, oferta e anúncio precisa de copy clara.",
    nextStep: "Comece testando títulos diferentes e veja qual gera mais cliques.",
  },
  {
    term: "CTA",
    category: "Marketing",
    meaning: "Chamada para ação. É a frase que diz para a pessoa o próximo passo.",
    purpose: "Guiar o visitante para fazer algo específico, como comprar ou se cadastrar.",
    example: "Botões como 'Começar agora' ou 'Quero garantir minha vaga' são CTAs.",
    whenNeeded: "Agora. Toda página precisa de um CTA visível.",
    nextStep: "Reveja seus posts e links: cada um tem uma CTA clara?",
  },
  {
    term: "Conversão",
    category: "Vendas",
    meaning: "Quando uma pessoa faz a ação que você queria, como comprar ou se cadastrar.",
    purpose: "Medir se seu funil está realmente funcionando.",
    example: "Se 100 pessoas visitam sua página e 3 compram, sua conversão é 3%.",
    whenNeeded: "Agora. Conversão é o sinal de que sua estratégia gera resultado.",
    nextStep: "Calcule sua conversão atual e teste uma mudança por vez para melhorar.",
  },
  {
    term: "Checkout",
    category: "Vendas",
    meaning: "A página onde o cliente finaliza a compra e faz o pagamento.",
    purpose: "Transformar interesse em venda concluída.",
    example: "A tela com formas de pagamento na Hotmart, Eduzz ou Stripe é o checkout.",
    whenNeeded: "Agora, assim que tiver um produto para vender.",
    nextStep: "Escolha uma plataforma simples para hospedar seu checkout e teste o fluxo.",
  },
  {
    term: "Nicho",
    category: "Marketing",
    meaning: "Um público específico, com uma dor ou interesse bem claro.",
    purpose: "Falar com quem realmente precisa, em vez de tentar agradar todo mundo.",
    example: "Em vez de 'finanças', um nicho é 'finanças para mães autônomas'.",
    whenNeeded: "Agora. Escolher um nicho é o que destrava tudo.",
    nextStep: "Anote 3 nichos que você conhece bem e escolha o mais promissor.",
  },
  {
    term: "Tráfego pago",
    category: "Marketing",
    meaning: "Visitas que chegam até você porque você pagou por anúncios.",
    purpose: "Acelerar o alcance sem depender só do algoritmo.",
    example: "Anúncios no Instagram, TikTok, Google ou YouTube.",
    whenNeeded: "Depois. Comece com tráfego orgânico até validar sua oferta.",
    nextStep: "Antes de pagar por anúncio, tenha uma oferta que já vendeu pelo menos uma vez.",
  },
  {
    term: "Tráfego orgânico",
    category: "Marketing",
    meaning: "Visitas que chegam sem você pagar, por conteúdo, indicação ou busca.",
    purpose: "Construir audiência e autoridade de forma sustentável.",
    example: "Um vídeo que viraliza no TikTok ou um texto que aparece no Google.",
    whenNeeded: "Agora. É a forma mais segura de começar.",
    nextStep: "Defina uma plataforma principal e publique de forma consistente.",
  },
  {
    term: "Afiliado",
    category: "Vendas",
    meaning: "Quem vende o produto de outra pessoa e recebe uma comissão por cada venda.",
    purpose: "Ganhar dinheiro sem precisar criar produto próprio.",
    example: "Recomendar um curso da Hotmart com seu link e receber por cada compra.",
    whenNeeded: "Agora. É uma das formas mais rápidas de começar.",
    nextStep: "Escolha 1 produto que você já usaria e crie conteúdo honesto sobre ele.",
  },
  {
    term: "Produto digital",
    category: "Produto digital",
    meaning: "Qualquer produto que pode ser entregue pela internet, sem estoque físico.",
    purpose: "Vender quantas vezes quiser sem custo de produção a cada venda.",
    example: "Ebooks, planners, templates, cursos, pacotes de prompts.",
    whenNeeded: "Agora. É o atalho clássico para gerar renda online.",
    nextStep: "Liste 3 ideias de produtos digitais baseados no que você já sabe fazer.",
  },
  {
    term: "Template",
    category: "Produto digital",
    meaning: "Um modelo pronto que outra pessoa pode usar como base.",
    purpose: "Economizar tempo de quem compra e gerar renda para quem cria.",
    example: "Templates de Notion, Canva, planilhas de controle financeiro.",
    whenNeeded: "Agora. Templates são produtos de venda rápida.",
    nextStep: "Escolha uma ferramenta que você domina e crie 1 template útil.",
  },
  {
    term: "Prompt",
    category: "IA",
    meaning: "A instrução que você dá para uma IA fazer alguma coisa.",
    purpose: "Tirar respostas melhores e mais úteis das ferramentas de IA.",
    example: "Em vez de 'escreva um post', um bom prompt diz tema, tom, formato e objetivo.",
    whenNeeded: "Agora. Saber escrever prompt vale por uma habilidade nova.",
    nextStep: "Pratique reescrevendo um prompt vago em um prompt detalhado.",
  },
  {
    term: "Landing page",
    category: "Marketing",
    meaning: "Uma página única feita para um objetivo específico, como vender ou capturar contato.",
    purpose: "Concentrar toda a atenção em uma decisão de cada vez.",
    example: "A página de inscrição de um curso ou de um webinar.",
    whenNeeded: "Agora, assim que tiver uma oferta para apresentar.",
    nextStep: "Monte uma landing page simples com promessa, prova e CTA.",
  },
  {
    term: "Onboarding",
    category: "Produto digital",
    meaning: "O processo que recebe o novo cliente ou usuário pela primeira vez.",
    purpose: "Reduzir confusão e fazer a pessoa enxergar valor logo no começo.",
    example: "Mensagens de boas-vindas, tutorial inicial, checklist de primeiros passos.",
    whenNeeded: "Agora, mesmo no produto mais simples.",
    nextStep: "Defina o primeiro 'momento de valor' que seu cliente deve viver.",
  },
  {
    term: "Churn",
    category: "SaaS",
    meaning: "A taxa de pessoas que cancelam ou param de pagar pelo seu produto.",
    purpose: "Mostrar se você está perdendo clientes mais rápido do que ganha.",
    example: "Se 100 pessoas assinam e 10 cancelam no mês, seu churn é 10%.",
    whenNeeded: "Depois, quando já tiver assinantes ativos.",
    nextStep: "Por enquanto, foque em conquistar os primeiros assinantes.",
  },
  {
    term: "MRR",
    category: "SaaS",
    meaning: "Receita Recorrente Mensal. Quanto você fatura todo mês com assinaturas.",
    purpose: "Acompanhar a saúde do negócio de forma previsível.",
    example: "10 clientes pagando R$39,90/mês geram R$399 de MRR.",
    whenNeeded: "Depois, quando começar a vender assinatura.",
    nextStep: "Foque primeiro em conseguir o primeiro cliente pagante.",
  },
  {
    term: "ARR",
    category: "SaaS",
    meaning: "Receita Recorrente Anual. É o MRR multiplicado por 12.",
    purpose: "Mostrar o tamanho do negócio em escala de ano.",
    example: "Um MRR de R$5.000 vira um ARR de R$60.000.",
    whenNeeded: "Depois. É métrica de negócio em crescimento.",
    nextStep: "Comece pequeno, valide a oferta e o ARR vem como consequência.",
  },
];

export const glossaryCategories: ("Todos" | GlossaryCategory)[] = [
  "Todos", "Vendas", "SaaS", "Marketing", "IA", "Produto digital",
];
